name: jogo_forca
description: Jogo da Forca - App Mobile com Flutter
publish_to: 'none'
version: 1.0.0+8

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0          # Banco de dados SQLite local
  path: ^1.8.3              # Para localizar o banco no dispositivo
  google_fonts: ^6.1.0      # Fontes bonitas
  flutter_animate: ^4.3.0   # Animações suaves
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/

  fonts:
    - family: FingerPaint
      fonts:
        - asset: assets/fonts/FingerPaint-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icone_app.png"
